// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Google_Play

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_appCard;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label5;
lv_obj_t *ui_appCard1;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label10;
lv_obj_t *ui_appCard2;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label16;
lv_obj_t *ui____initial_actions0;
const lv_image_dsc_t *ui_imgset_[2] = {&ui_img_1_png, &ui_img_2_png};
const lv_image_dsc_t *ui_imgset_42262729[1] = {&ui_img_190695247};
const lv_image_dsc_t *ui_imgset_1440576951[1] = {&ui_img_997471977};
const lv_image_dsc_t *ui_imgset_98136657[1] = {&ui_img_1475871244};
const lv_image_dsc_t *ui_imgset_612449719[1] = {&ui_img_1644947644};
const lv_image_dsc_t *ui_imgset_1897438134[1] = {&ui_img_1214273956};
const lv_image_dsc_t *ui_imgset_wallpaper_[1] = {&ui_img_wallpaper_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 16
//     #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}

void add_app(const char* name, const char* version, const char* category, float rate, int installs)
{
    ui_appCard = lv_obj_create(ui_Panel1);
    lv_obj_set_width( ui_appCard, 250);
    lv_obj_set_height( ui_appCard, 220);
    lv_obj_set_align( ui_appCard, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_appCard,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_appCard, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag( ui_appCard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_border_color(ui_appCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_appCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_appCard, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_appCard);
    lv_obj_set_width( ui_Label1, 240);
    lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label1,name);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_appCard);
    lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label2, version);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_appCard);
    lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label3,category);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_appCard);
    lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
    lv_label_set_text_fmt(ui_Label4, "%.2f", rate);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_appCard);
    lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
    lv_label_set_text_fmt(ui_Label5,"%d", installs);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

}

