// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Google_Play

#ifndef _GOOGLE_PLAY_UI_H
#define _GOOGLE_PLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_appCard;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_appCard1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_appCard2;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1_png);   // assets/1.png
LV_IMG_DECLARE( ui_img_2_png);   // assets/2.png
LV_IMG_DECLARE( ui_img_190695247);   // assets/cancel-128.png
LV_IMG_DECLARE( ui_img_997471977);   // assets/check-128.png
LV_IMG_DECLARE( ui_img_1475871244);   // assets/flx-200.png
LV_IMG_DECLARE( ui_img_1644947644);   // assets/flx-white-200.png
LV_IMG_DECLARE( ui_img_1214273956);   // assets/rfid-128.png
LV_IMG_DECLARE( ui_img_wallpaper_1_png);   // assets/wallpaper_1.png




void ui_init(void);
void add_app(const char* name, const char* version, const char* category, float rate, int installs);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
